### ISSUE TITLE
broccoli-caching-writer/rimraf throws error on build

### ISSUE THREAD

**Issue by ghost** [apolzon/ember-cli-refills-components#2]
Log+trace:

```
➤ ember server
version: 0.1.2
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
TypeError: Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
    at rimraf (/home/user/emberschool/ember-cli-refills-components/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:58:13)
    at lib$rsvp$node$$tryApply (/home/user/emberschool/ember-cli-refills-components/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1467:11)
    at lib$rsvp$node$$handleValueInput (/home/user/emberschool/ember-cli-refills-components/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1567:20)
    at fn (/home/user/emberschool/ember-cli-refills-components/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1555:18)
    at /home/user/emberschool/ember-cli-refills-components/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:100:14
    at lib$rsvp$$internal$$tryCatch (/home/user/emberschool/ember-cli-refills-components/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/user/emberschool/ember-cli-refills-components/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/user/emberschool/ember-cli-refills-components/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:472:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/home/user/emberschool/ember-cli-refills-components/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by apolzon** [comment]
Thanks for reporting this. Unfortunately I'm not using refills anymore, so I'm not sure when I can get around to fixing this. I'm happy to add you as a collaborator on ember-addons for the project, or transfer ownership to you (although I don't see any options to do that on ember-addons site).

**Comment by ghost** [comment]
No problem. I don't have any time to work on this either, though I think the repo is a good resource even as guidelines.
